var canvas,context,curTime=0,wWidth=0,wHeight=0,centerX=0,centerY=0,allCircles=[],nextCircle,nextId=0,maxR=0,nw=128,nh=80,hash=BuildHash(nw,nh),colors=["rgb(20,10,30)","rgb(80,10,30)","rgb(140,10,30)","rgb(200,10,30)","rgb(255,10,30)"],cSize=colors.length;function ColorD(){return Math.floor(0.99*Math.random()*cSize)}function MaxR(a,d,b,h){return 0.5*Math.min(b/a,h/d)}
function SpatialHash(a,d,b,h){this.nw=a;this.nh=d;this.maxw=b;this.maxh=h;this.fw=a/b;this.fh=d/h;this.dw=b/a;this.dh=h/d;this.bucket=[];this.Clear=function(){for(var a=0;a<this.nw*this.nh;a+=1)this.bucket[a]=[]};this.GetCircleIds=function(a){var c=0.5*this.maxw,d=0.5*this.maxh,g=[],e=Math.floor((a.x+c)*this.fw),f=Math.floor((a.y+d)*this.fh);0<=e&&(e<this.nw&&0<=f&&f<this.nh)&&(g[f*this.nw+e]=!0);tests=[-1,-1,-1,1,1,-1,1,1];for(e=0;4>e;e+=1){var f=Math.floor((a.x+tests[2*e]*a.r+c)*this.fw),b=Math.floor((a.y+
tests[2*e+1]*a.r+d)*this.fh);0<=f&&(f<this.nw&&0<=b&&b<this.nh)&&(g[b*this.nw+f]=!0)}return g};this.MaxR=function(){return MaxR(this.nw,this.nh,this.maxw,this.maxh)};this.DrawBucket=function(){context.font="30px Verdana";context.fillStyle="#000000";for(var b=0;b<d;b+=1)for(var c=0;c<a;c+=1)context.fillText(this.bucket[b*this.nw+c],(c+0.5)*this.dw,(b+0.5)*this.dh)}}
function BuildHash(a,d){hash=new SpatialHash(a,d,wWidth,wHeight);hash.Clear();for(circleId in allCircles)for(id in allCircles[circleId].hashIds=hash.GetCircleIds(allCircles[circleId]),allCircles[circleId].hashIds)hash.bucket[id][hash.bucket[id].length]=circleId;return hash}
function Circle(){this.py=this.px=this.y=this.x=0;this.r=10;this.r2=this.r*this.r;this.colorD=ColorD();this.draw=function(a){a.fillStyle=this.color;a.beginPath();a.arc(centerX+this.x,centerY+this.y,this.r,0,2*Math.PI);a.closePath();a.fill()};this.setup=function(){this.r2=this.r*this.r;this.px=this.x;this.py=this.y;this.color=colors[this.colorD]};this.setup()}var gravity=new function(){this.x=0;this.y=-9.8};
function moveHandler(a){nextCircle.x=a.pageX-wWidth/2+80*Math.random()-40;nextCircle.y=a.pageY-wHeight/2+80*Math.random()-40;nextCircle.r=1.4+0.7*Math.random()*maxR;a=nextId;nextId+=1;allCircles[a]=nextCircle;allCircles[a].setup();nextCircle=new Circle;nextCircle.r=maxR}function clickHandler(){delete allCircles;allCircles=[]}function hashProcess(){hash=BuildHash(nw,nh)}
function integrate(a){var a=a*a;for(circleId in allCircles){var h=0.5*(-allCircles[circleId].x),j=0.5*(-allCircles[circleId].y);for(hashId in allCircles[circleId].hashIds)for(var c=0;c<hash.bucket[hashId].length;c+=1)if(circle2Id=hash.bucket[hashId][c],circleId!=circle2Id){var i=allCircles[circle2Id].x-allCircles[circleId].x,g=allCircles[circle2Id].y-allCircles[circleId].y,e=allCircles[circle2Id].r+allCircles[circleId].r,f=
i*i+g*g;f<e*e&&(f1=allCircles[circleId].r2/(allCircles[circleId].r2+allCircles[circle2Id].r2),dl=Math.sqrt(f),diff=(dl-e)/dl,allCircles[circleId].x+=i*(1-f1)*diff,allCircles[circleId].y+=g*(1-f1)*diff,allCircles[circle2Id].x-=i*f1*diff,allCircles[circle2Id].y-=g*f1*diff,allCircles[circle2Id].colorD===allCircles[circleId].colorD&&(allCircles[circleId].colorD=ColorD(),allCircles[circle2Id].colorD=ColorD(),allCircles[circleId].color=colors[allCircles[circleId].colorD],allCircles[circle2Id].color=colors[allCircles[circle2Id].colorD]))}c=
allCircles[circleId].x;i=allCircles[circleId].y;allCircles[circleId].x=2*allCircles[circleId].x-allCircles[circleId].px+h*a;allCircles[circleId].y=2*allCircles[circleId].y-allCircles[circleId].py+j*a;allCircles[circleId].px=c;allCircles[circleId].py=i}}
function gameInit(){function a(){canvas.width=window.innerWidth;canvas.height=window.innerHeight;wWidth=canvas.width;wHeight=canvas.height;centerX=wWidth/2;centerY=wHeight/2}canvas=document.getElementById("canvas");context=canvas.getContext("2d");a();window.addEventListener("resize",a,!1);window.addEventListener("mousedown",clickHandler,!1);window.addEventListener("mousemove",moveHandler,!1);setInterval(gameRender,33);setInterval(function(){curTime+=0.0333},33);setInterval(function(){integrate(0.0333)},
33);setInterval(hashProcess,33);maxR=MaxR(nw,nh,wWidth,wHeight);nextId=allCircles.length;nextCircle=new Circle}
function gameRender(){context.clearRect(0,0,wWidth,wHeight);for(circleId in allCircles)context.fillStyle=allCircles[circleId].color,context.beginPath(),context.arc(centerX+allCircles[circleId].x,centerY+allCircles[circleId].y,allCircles[circleId].r,0,2*Math.PI),context.closePath(),context.fill();context.font="10px Verdana";context.fillStyle="#000";context.fillText("Lukas Steiblys, http://imbusy.org",wWidth-195,wHeight-10)};
